export const SkillsImg = [
  { skill: "Python", descricao: "Linguagem de alto nível, interpretada, com tipagem dinâmica e multiplataforma, criada por Guido van Rossum em 1991.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307714/Python_kwurnx.jpg", altText: "Logo da linguagem de programação Python" },
  { skill: "Java", descricao: "Java é uma linguagem de programação de alto nível, orientada a objetos e multiplataforma, criada pela Sun Microsystems em 1995.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307795/Java1_hnquey.png", altText: "Logo da linguagem de programação Java" },
  { skill: "JavaScript", descricao: "JavaScript é uma linguagem de alto nível, interpretada, dinâmica e multiplataforma, criada por Brendan Eich em 1995.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307755/Javascript_gabq2p.jpg", altText: "Logo da linguagem de programação Javascript" },
  { skill: "C++", descricao: "C++ é uma linguagem de alto nível, compilada, com suporte a orientação a objetos, criada por Bjarne Stroustrup em 1985.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307673/C_frui5d.jpg", altText: "Logo da linguagem de programação C++" },
  { skill: "Ruby", descricao: "Ruby é uma linguagem de alto nível, interpretada, com foco na simplicidade e produtividade, criada por Y. Matsumoto em 1995.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307880/Ruby_ezsxap.jpg", altText: "Logo da linguagem de programação Ruby" },
  { skill: "Go", descricao: "Golang é uma linguagem de alto nível, compilada e concorrente, criada pelo Google em 2009.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/f_auto,q_auto,w_400/Golang_xczcij.png", altText: "Logo da linguagem de programação Golang" },
  { skill: "C#", descricao: "C# é uma linguagem de alto nível, orientada a objetos e compilada, criada pela Microsoft em 2000.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307531/C_ktxyfw.jpg", altText: "Logo da linguagem de programação C#" },
  { skill: "Swift", descricao: "Swift é uma linguagem de programação de alto nível, compilada e moderna, criada pela Apple em 2014.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750308044/swift_shp4h0.png", altText: "Logo da linguagem de programação Swift" },
  { skill: "Kotlin", descricao: "Kotlin é uma linguagem de alto nível, concisa e orientada a objetos, criada pela JetBrains em 2011.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750308002/Kotlin_zweekw.png", altText: "Logo da linguagem de programação Kotlin" },
  { skill: "PHP", descricao: "PHP é uma linguagem de alto nível, interpretada e focada em web, criada por Rasmus Lerdorf em 1995.", image: "https://res.cloudinary.com/dptl0qlqr/image/upload/v1750307934/PHP_mm1hfi.jpg", altText: "Logo da linguagem de programação PHP" },
];